In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'a':[0, 1, 2, 3], 'b':[4, 5, 6, 7]})
df

a  b
0  0  4
1  1  5
2  2  6
3  3  7

In [4]:
df2 = df.applymap(lambda x: 2*x)
df2

a   b
0  0   8
1  2  10
2  4  12
3  6  14

In [5]:
df3 = df.apply(np.mean)
df3

a    1.5
b    5.5
dtype: float64

In [8]:
df4 = df.apply(np.mean, axis=1)
df4

0    2
1    3
2    4
3    5
dtype: float64

In [21]:
df5 = df.apply(lambda x: x.ix[1], axis = 1)
df5

0    4
1    5
2    6
3    7
dtype: int64

In [18]:
ser = pd.Series(['a','b','b'])
ser

0    a
1    b
2    b
dtype: object

In [24]:
mat = np.array([[0,1,2],[3,4,5],[6,7,8]])
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.dot(mat,mat)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [32]:
ls = [x for x in zip(np.arange(0,5), np.arange(6,11))]
ls

[(0, 6), (1, 7), (2, 8), (3, 9), (4, 10)]

In [42]:
x = np.arange(0,5)
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [48]:
if 3:
    print('lalal')

lalal
